apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  TEST_ENV: test

# --- で区切ることができる
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: k8s.gcr.io/busybox
    command: ["env"] # print env var
    # ここ↓で上のConfigMapを指定
    envFrom:
    - configMapRef:
        name: test-config
